name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Cargo Check
      run: cargo check --workspace
    - name: Run Cargo Test
      run: cargo test --workspace
    - name: Run Cargo Clippy
      run: cargo clippy --workspace -- -D warnings
    - name: Run Cargo Fmt
      run: cargo fmt --all -- --check